// Localhost routes
GET http://localhost:3000/contacts
###

GET http://localhost:3000/contacts/6336562857002fc5767eec79
###

POST http://localhost:3000/contacts/
content-type: application/json

{
	"firstName": "Paola",
	"lastName": "Qosja",
	"email": "pola@gmail.com",
	"favoriteColor": "yellow",
	"birthday": "1970-08-27"
}
###

PUT http://localhost:3000/contacts/6336533457002fc5767eec6b
content-type: application/json

{
	"email": "xyz@yahoo.com"
}
###

DELETE http://localhost:3000/contacts/6336533257002fc5767eec67
###

// Render routes
GET https://ammonquarshiecontactsapi.onrender.com/contacts
###

GET https://ammonquarshiecontactsapi.onrender.com/contacts/63426e4b8b220438f1694cd8
###

POST https://ammonquarshiecontactsapi.onrender.com/contacts
content-type: application/json

{
	"firstName": "Princess",
	"lastName": "Fiona",
	"email": "shrek@gmail.com",
	"favoriteColor": "green",
	"birthday": "30 A.D."
}
###

PUT https://ammonquarshiecontactsapi.onrender.com/contacts/63426e4b8b220438f1694cd8
content-type: application/json

{
	"email": "xyz@yahoo.com"
}
###

DELETE https://ammonquarshiecontactsapi.onrender.com/contacts/63426e4b8b220438f1694cd8
###