GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/6336562857002fc5767eec79

###

POST http://localhost:3000/contacts/
content-type: application/json

{
	"firstName": "Paola",
	"lastName": "Qosja",
	"email": "pola@gmail.com",
	"favoriteColor": "yellow",
	"birthday": "1970-08-27"
}
###

PUT http://localhost:3000/contacts/6336533457002fc5767eec6b
content-type: application/json

{
	"email": "xyz@yahoo.com"
}
###

DELETE http://localhost:3000/contacts/6336533257002fc5767eec67